apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-p-baconend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chris-p-baconend
  template:
    metadata:
      labels:
        app: chris-p-baconend
    spec:
      containers:
        - name: chris-p-baconend
          image: dauer23/chrispbaconend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: APP_SECRET            
---
apiVersion: v1
kind: Service
metadata:
  name: chris-p-baconend-service
spec:
  selector:
    app: chris-p-baconend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort