apiVersion: v1
kind: Secret
metadata:
  name: db
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded password
  POSTGRES_PASSWORD: MTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  APP_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MDEyMzk0dTUzOTg0ejU5M3o0NTkyMzQyMzQ0YXNkam5rYWpzCg==
